/* Catálogo de cursos locales → landings */
window.ACACODE_COURSES = [
  {
    slug: "minigenio-scratch",
    title: "MiniGenios: Scratch y Animación",
    category: "Mini Genios",
    blurb: "Lógica, videojuegos y animaciones con bloques de Scratch.",
    hours: "32h",
    image: "cursos/minigenio-scratch/img/hero-minigenio-scratch.png",
    href: "cursos/minigenio-scratch/index.html",
  },
  {
    slug: "minigenio-stem",
    title: "MiniGenio Módulo III: Habilidades STEM",
    category: "Mini Genios",
    blurb: "STEM para 7–14 años: estructuras, carro solar, carrusel y avión de pista.",
    hours: "32h",
    image: "cursos/minigenio-stem/img/hero-minigenio-stem.png",
    href: "cursos/minigenio-stem/index.html",
  },
  {
    slug: "marketing-digital",
    title: "Marketing Digital",
    category: "Marketing",
    blurb: "SEO, email, afiliados y contenido para escalar tu negocio.",
    hours: "16h",
    image: "cursos/marketing-digital/img/hero-marketing-digital.png",
    href: "cursos/marketing-digital/index.html",
  },
  {
    slug: "python",
    title: "Python: De cero a programador",
    category: "Programación",
    blurb: "Aprende Python desde cero con práctica real.",
    hours: "12h",
    image: "cursos/python/img/hero-python.png",
    href: "cursos/python/index.html",
  },
  {
    slug: "python-ii",
    title: "Python: «De Cero a Programador» II",
    category: "Programación",
    blurb: "Arquitectura profesional, POO, patrones de diseño y calidad de software.",
    hours: "16h",
    image: "cursos/python-ii/img/hero-python-modulo-ii.png",
    href: "cursos/python-ii/index.html",
  },
  {
    slug: "ia-generativa",
    title: "IA Generativa desde Cero",
    category: "Inteligencia Artificial",
    blurb: "Herramientas de IA para trabajo, estudio y negocio.",
    hours: "16h",
    image: "cursos/ia-generativa/img/hero-ia-generativa.png",
    href: "cursos/ia-generativa/index.html",
  },
  {
    slug: "logica-programacion",
    title: "Fundamentos de Programación I",
    category: "Programación",
    blurb: "Lógica, algoritmos y el ADN del programador.",
    hours: "16h",
    image: "cursos/logica-programacion/img/hero-logica-programacion.png",
    href: "cursos/logica-programacion/index.html",
  },
  {
    slug: "logica-programacion-ii",
    title: "Fundamentos de Programación II",
    category: "Programación",
    blurb: "Datos, calidad de código y POO.",
    hours: "16h",
    image: "cursos/logica-programacion-ii/img/hero-logica-programacion-ii.png",
    href: "cursos/logica-programacion-ii/index.html",
  },
  {
    slug: "alfabetizacion-tecnologica",
    title: "Alfabetización Tecnológica I",
    category: "Alfabetización",
    blurb: "Entorno físico, lógico e información con autonomía.",
    hours: "16h",
    image: "cursos/alfabetizacion-tecnologica/img/hero-alfabetizacion-tecnologica.png",
    href: "cursos/alfabetizacion-tecnologica/index.html",
  },
  {
    slug: "hoja-calculo",
    title: "Hoja de Cálculo I",
    category: "Alfabetización",
    blurb: "De cero a la gestión de datos.",
    hours: "16h",
    image: "cursos/hoja-calculo/img/hero-hoja-calculo.png",
    href: "cursos/hoja-calculo/index.html",
  },
  {
    slug: "hoja-calculo-ii",
    title: "Hoja de Cálculo Nivel Medio",
    category: "Alfabetización",
    blurb: "Fórmulas, análisis y productividad intermedia.",
    hours: "16h",
    image: "cursos/hoja-calculo-ii/img/hero-hoja-calculo-ii.png",
    href: "cursos/hoja-calculo-ii/index.html",
  },
  {
    slug: "web-developer",
    title: "Web Developer: HTML, CSS y JS",
    category: "Programación",
    blurb: "Construye sitios web desde cero.",
    hours: "16h",
    image: "cursos/web-developer/img/hero-curso.png",
    href: "cursos/web-developer/index.html",
  },
];
